import {Global} from "@/styles/global";
import {Dimensions, StyleSheet} from "react-native";

const {width: SCREEN_WIDTH} = Dimensions.get("window");

export const AllocateFarmingScreenStyles = StyleSheet.create({
  container: {
    width: "100%",
    height: "100%",
    flex: 1,
    backgroundColor: "#F5F6F8",
  },
  content: {
    flex: 1,
    padding: 10,
    marginBottom: 100,
  },
  popupTips: {
    width: SCREEN_WIDTH,
    height: 38,
    backgroundColor: "#FFF3F2",
    justifyContent: "center",
    alignItems: "center",
  },
  popupTipsText: {
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 38,
    color: "#333",
    textAlign: "center",
  },
  popupTipsActiveText: {
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 38,
    color: "#FF3D3B",
  },
  sectionContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    padding: 16,
    maxHeight: 600,
    marginBottom: 10,
    elevation: 1,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "500",
    color: "#000",
  },
  farmingType: {
    marginLeft: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    backgroundColor: Global.colors.primary,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  farmingTypeText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#fff",
  },
  landSelectBtn: {
    width: "100%",
    minHeight: 52,
    borderRadius: 8,
    backgroundColor: "#F5F6F8",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginBottom: 6,
  },
  landSelectText: {
    fontSize: 16,
    color: "#999",
    fontWeight: "500",
  },
  selectLandTextContnet: {
    flex: 1,
    flexDirection: "column",
  },
  selectLandText: {
    fontSize: 16,
    color: "#333",
    fontWeight: "500",
  },
  nameInputContainer: {
    width: "100%",
    height: 52,
    borderRadius: 8,
    backgroundColor: "#F5F5F5",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    position: "relative",
    marginBottom: 8,
  },
  nameInput: {
    flex: 1,
    fontSize: 16,
    color: "#000",
    height: "100%",
    fontWeight: "500",
  },
  editIcon: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  editIconImg: {
    width: 20,
    height: 20,
  },
  addAllocateFarmingContainer: {
    marginBottom: 20,
  },
  addAllocateFarming: {
    flexDirection: "row",
    width: "100%",
    height: 52,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 16,
    borderRadius: 8,
    backgroundColor: "#fff",
  },
  addAllocateFarmingImg: {
    width: 26,
    height: 26,
  },
  addAllocateFarmingText: {
    marginLeft: 8,
    fontSize: 16,
    fontWeight: "500",
    color: Global.colors.primary,
  },
  btnSave: {
    position: "absolute",
    bottom: 0,
    left: 0,
    width: SCREEN_WIDTH,
    height: 84,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    elevation: 1,
  },
  btnDisabled: {
    opacity: 0.5,
  },
  btn: {
    width: 343,
    height: 52,
    backgroundColor: Global.colors.primary,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  btnText: {
    fontSize: 20,
    fontWeight: "500",
    color: "#fff",
  },
  mask: {
    position: "absolute",
    top: 0,
    left: 0,
    width: SCREEN_WIDTH,
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 2000,
  },
  popupBox: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  popupContent: {
    width: 280,
    backgroundColor: "#fff",
    borderRadius: 8,
    alignItems: "center",
    overflow: "hidden",
    elevation: 4,
  },
  popupContentTop: {
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    marginTop: 12,
  },
  titleText: {
    fontSize: 20,
    fontWeight: "500",
    color: "#000",
  },
  msg: {
    marginHorizontal: 24,
    marginVertical: 16,
  },
  msgText: {
    fontSize: 18,
    fontWeight: "400",
    color: "#000",
    textAlign: "left",
  },
  divider: {
    width: "100%",
    height: 1,
    backgroundColor: "#ededed",
  },
  popupBottom: {
    flexDirection: "row",
    alignItems: "center",
    height: 51,
    width: "100%",
  },
  btnLeft: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  btnRight: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  leftText: {
    fontSize: 18,
    fontWeight: "500",
    color: "#000",
  },
  rightText: {
    fontSize: 18,
    fontWeight: "500",
    color: Global.colors.primary,
  },
  cross: {
    width: 1,
    height: 24,
    backgroundColor: "#ededed",
  },
});
