import {Global} from "@/styles/global";
import {Dimensions, StyleSheet} from "react-native";
import {Platform, StatusBar} from "react-native";

const STATUS_BAR_HEIGHT = Platform.OS === "ios" ? 44 : StatusBar.currentHeight || 0;
const {width: SCREEN_WIDTH} = Dimensions.get("window");
export const MyScreenStyles = StyleSheet.create({
  container: {flex: 1, backgroundColor: "#f7f7f8"},
  topBg: {width: SCREEN_WIDTH, height: 280, paddingTop: STATUS_BAR_HEIGHT},
  topIcon: {position: "absolute", top: STATUS_BAR_HEIGHT + 9, right: 16, zIndex: 10},
  iconImg: {width: 24, height: 24},
  userInfoRow: {flexDirection: "row", alignItems: "center", paddingLeft: 21},
  avatarContainer: {width: 70, height: 70},
  avatar: {width: 70, height: 70, borderRadius: 35},
  msgContainer: {flex: 1, marginLeft: 12},
  name: {fontSize: 20, fontWeight: "500", color: Global.colors.textLight},
  phoneAuthRow: {flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between"},
  phoneRow: {flexDirection: "row", alignItems: "center"},
  phoneIcon: {width: 20, height: 20},
  phoneText: {fontSize: 16, marginLeft: 3, color: Global.colors.textLight},
  authBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 12,
    paddingVertical: 4,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
  },
  authDone: {backgroundColor: "#CBF8D9"},
  authPending: {backgroundColor: "#FFE1E1"},
  authDoneText: {color: Global.colors.primary},
  authPendingText: {color: "#FF3D3B"},
  authIcon: {width: 12, height: 12, marginHorizontal: 5},
  dataRow: {flexDirection: "row", justifyContent: "space-between", marginTop: 27, paddingHorizontal: 21},
  dataItem: {alignItems: "center"},
  dataNum: {fontSize: 18, color: Global.colors.textLight, fontWeight: "600"},
  dataLabel: {fontSize: 14, color: Global.colors.textLight, marginTop: 4},
  hostedOrdersBox: {backgroundColor: "#fff", marginTop: -40, paddingVertical: 16},
  hostedOrdersTop: {flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 16},
  orderTitle: {fontSize: 16, fontWeight: "500", color: "#333"},
  orderMore: {flexDirection: "row", alignItems: "center"},
  orderMoreText: {fontSize: 14, color: "#666"},
  iconSmall: {width: 12, height: 12, marginLeft: 4},
  orderList: {flexDirection: "row", justifyContent: "space-around"},
  orderItem: {alignItems: "center", width: SCREEN_WIDTH / 4, marginTop: 16},
  ordersItemIcon: {position: "relative"},
  orderIcon: {width: 32, height: 32},
  orderName: {marginTop: 6, fontSize: 14, color: Global.colors.textDark},
  badgeContainer: {
    position: "absolute",
    top: -5,
    right: -5,
    backgroundColor: "#F25643",
    borderRadius: 8,
    minWidth: 16,
    height: 16,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 4,
  },
  largeBadge: {right: -10},
  badgeText: {
    color: "white",
    fontSize: 10,
    fontWeight: "bold",
  },
  manageList: {flexDirection: "row", flexWrap: "wrap", backgroundColor: "#fff", marginTop: 10, paddingBottom: 20},
  mangeItem: {width: SCREEN_WIDTH / 3, alignItems: "center", marginTop: 20},
  mangeIcon: {width: 40, height: 40, marginBottom: 12},
  mangeText: {fontSize: 16, fontWeight: "500", color: Global.colors.textDark},
  popupBox: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 10,
  },
  popupContent: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -37%)",
    width: SCREEN_WIDTH * 0.83,
    height: 388,
    backgroundColor: "#fff",
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: {width: 0, height: -4},
    shadowOpacity: 0.1,
    shadowRadius: 12,
    alignItems: "center",
  },
  popupContentMain: {
    width: "100%",
    alignItems: "center",
    overflow: "hidden",
  },
  popupTopRadius: {
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  popupContentTop: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    marginTop: 18,
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#000",
    marginBottom: 12,
  },
  msg: {
    fontSize: 15,
    fontWeight: "500",
    color: "#000",
    marginBottom: 20,
    lineHeight: 22,
  },
  authFrom: {
    width: "100%",
    paddingHorizontal: 24,
  },
  label: {
    fontSize: 14,
    color: "#333",
    marginBottom: 8,
  },
  popupInput: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    height: 48,
    backgroundColor: "#eff2f3",
    borderRadius: 8,
    paddingHorizontal: 16,
  },
  input: {
    flex: 1,
    height: "100%",
    fontSize: 15,
  },
  popupImg: {
    width: 24,
    height: 24,
    marginLeft: 8,
  },
  scanIcon: {
    width: "100%",
    height: "100%",
  },
  divider: {
    width: "90%",
    height: 1,
    backgroundColor: "#ededed",
    marginTop: 30,
    marginVertical: 8,
  },
  popupBottom: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    height: 51,
  },
  btnLeft: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
  },
  btnLeftText: {
    fontSize: 15,
    fontWeight: "500",
    color: "#000",
  },
  cross: {
    width: 1,
    height: "60%",
    backgroundColor: "#ededed",
  },
  btnRight: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
  },
  btnRightText: {
    fontSize: 15,
    fontWeight: "500",
  },
  activeBtnText: {
    color: "#08ae3c",
    opacity: 1,
  },
  inactiveBtnText: {
    color: "#08ae3c",
    opacity: 0.5,
  },
});
