import {Global} from "@/styles/global";
import {Dimensions, StyleSheet} from "react-native";
const {width} = Dimensions.get("window");
export const LandDetailsPopupStyles = StyleSheet.create({
  container: {
    position: "absolute",
    left: 0,
    bottom: 0,
    width: width,
    zIndex: 1999,
    backgroundColor: Global.colors.textLight,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  expand: {
    position: "absolute",
    top: -24,
    left: "50%",
    transform: [{translateX: "-50%"}],
  },
  iconImg: {
    width: 64,
    height: 24,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginHorizontal: 16,
    marginTop: 12,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 500,
    color: Global.colors.textDark,
  },
  iconBtn: {
    width: 26,
    height: 26,
  },
  tabContainer: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  tabButton: {
    marginTop: 10,
    flex: 1,
    alignItems: "center",
  },
  tabText: {
    fontSize: 16,
  },
  activeTabText: {
    fontSize: 20,
    fontWeight: "500",
    color: Global.colors.primary,
  },
  inactiveTabText: {
    fontSize: 20,
    color: "#666",
  },
  tabItem: {
    flexDirection: "column",
    alignItems: "center",
  },
  inactiveTabLine: {
    width: 70,
    height: 3,
    backgroundColor: Global.colors.primary,
  },
  infoLand: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: width,
    height: 52,
    paddingHorizontal: 8,
    marginTop: 8,
  },
  landInfo: {
    maxWidth: 230,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  landInfoName: {
    flex: 1,
    maxWidth: "80%",
    fontSize: 24,
    fontWeight: "500",
  },
  landInfoType: {
    width: 64,
    height: 24,
    marginLeft: 8,
    borderRadius: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  landInfoTypeText: {
    fontSize: 16,
    fontWeight: "500",
    lineHeight: 24,
    color: "#fff",
    textAlign: "center",
  },
  landNumber: {
    fontSize: 24,
    fontWeight: "500",
  },
  landNumberUnit: {
    fontSize: 17,
  },
  infoContent: {
    width: "100%",
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  infoContentItem: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "flex-start",
    marginTop: 10,
    alignItems: "center",
  },
  phoneImage: {
    width: 24,
    height: 24,
    marginLeft: 8,
  },
  infoContentItemTitle: {
    maxWidth: 90,
    fontSize: 18,
    fontWeight: "400",
    color: "rgba(0, 0, 0, 0.65)",
    textAlign: "left",
  },
  infoContentItemText: {
    flex: 1,
    fontSize: 18,
    fontWeight: "400",
    color: "#000",
  },
  infoLocation: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  contractInfo: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
    paddingHorizontal: 16,
  },
  contractNoContainer: {
    maxWidth: 240,
  },
  contractNoText: {
    fontSize: 24,
    fontWeight: "500",
  },
  infoContentItemRow: {
    width: "100%",
    flexDirection: "row",
  },
  contractInfoItem: {
    width: "50%",
    flexDirection: "row",
    justifyContent: "flex-start",
    marginTop: 10,
    alignItems: "center",
  },
  contractEmpty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyImage: {
    width: 87,
    height: 79,
    marginTop: 34,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "400",
    color: "#000",
  },
  addContract: {
    width: 122,
    height: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    marginTop: 16,
    borderWidth: 1,
    borderRadius: 6,
    borderColor: Global.colors.primary,
  },
  addContractText: {
    fontSize: 18,
    fontWeight: "400",
    color: Global.colors.primary,
  },
  msgOrder: {
    width: width,
    height: 280,
  },
  msgOrdeItem: {
    paddingTop: 16,
    paddingRight: 11,
    paddingLeft: 26,
  },
  msgOrdeItemContent: {
    position: "relative",
    width: "100%",
    height: 120,
  },
  timelineLine: {
    position: "absolute",
    top: 15,
    left: -13,
    width: 2,
    height: 128,
    backgroundColor: "#ccc",
  },
  lastTimelineLine: {
    height: 0,
  },
  timelineDot: {
    position: "absolute",
    top: 7,
    left: -17,
    width: 10,
    height: 10,
    backgroundColor: "#ccc",
    borderRadius: 5,
  },
  contentTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 8,
  },
  time: {
    fontSize: 16,
    fontWeight: "500",
  },
  contentMain: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 13,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#e7e7e7",
  },
  farmingInfo: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  farmingInfoContent: {
    flexDirection: "row",
  },
  msgImage: {
    width: 156 / 2,
    height: 156 / 2,
  },
  msgText: {
    height: 156 / 2,
    marginLeft: 12,
    flexDirection: "column",
    justifyContent: "space-between",
  },
  title: {
    maxWidth: 175,
    fontSize: 18,
    fontWeight: "500",
  },
  price: {
    fontSize: 20,
    fontWeight: "500",
    color: "#ff3d3b",
    marginBottom: 8,
  },
  farmingType: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: 54,
    height: 22,
    fontSize: 14,
    fontWeight: "500",
    borderRadius: 2,
  },
  footButton: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
  },
  footButtonItem: {
    flex: 1,
    height: 52,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
  },
  buttonText: {
    fontSize: 20,
    fontWeight: "500",
    color: "#fff",
  },
  yellow: {
    backgroundColor: "#f58700",
  },
  green: {
    backgroundColor: Global.colors.primary,
  },
  blue: {
    backgroundColor: "#007cff",
  },
});
