import {Global} from "@/styles/global";
import {Dimensions, StyleSheet} from "react-native";

const {width} = Dimensions.get("window");

export const EnclosureScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  mapBox: {flex: 1},
  popupTips: {
    position: "absolute",
    top: 94,
    left: 0,
    zIndex: 999,
    width: width,
    height: 38,
    backgroundColor: "#ffda00",
    justifyContent: "center",
    alignItems: "center",
  },
  popupTipsText: {
    fontSize: 16,
    fontWeight: "500",
    lineHeight: 38,
    color: "#000",
    textAlign: "center",
  },
  rightControl: {
    position: "absolute",
    top: 140,
    right: 16,
  },
  locationControl: {
    position: "absolute",
    bottom: 120,
    right: 16,
  },
  map: {flex: 1},
  mapCopyright: {position: "absolute", bottom: 0, left: 0, flexDirection: "row", alignItems: "flex-end"},
  iconImg: {width: 40, height: 20},
  copyrightText: {fontSize: 8, color: "#fff"},
  footerButtonGroup: {
    position: "absolute",
    bottom: 21,
    left: 0,
    zIndex: 1000,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    width: "100%",
    paddingHorizontal: 34,
  },
  buttonBase: {
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonRevoke: {
    width: 70,
    height: 70,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
  },
  revokeText: {fontSize: 18, fontWeight: "500", color: "#ff3d3b"},
  buttonDot: {
    width: 100,
    height: 100,
    backgroundColor: Global.colors.primary,
    borderWidth: 4,
    borderColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 12},
    shadowOpacity: 0.16,
    shadowRadius: 16,
    elevation: 6,
  },
  dotIcon: {width: 30, height: 30, marginBottom: 4},
  dotText: {fontSize: 18, fontWeight: "500", color: "#fff"},
  buttonSave: {
    width: 70,
    height: 70,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
  },
  saveText: {fontSize: 18, fontWeight: "500"},
  placeholder: {width: 70, height: 70},
  locationCursor: {
    position: "absolute",
    top: "50%",
    left: "50%",
    zIndex: 1010,
    transform: [{translateX: -20}, {translateY: -20}],
  },
  cursorIcon: {width: 40, height: 40, resizeMode: "contain"},
  landType: {
    position: "absolute",
    bottom: 120,
    left: 16,
    alignItems: "center",
    justifyContent: "space-around",
    width: 86,
    height: 76,
    backgroundColor: "rgba(0,0,0,0.7)",
    elevation: 5,
  },
  landTypeItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  icon: {
    width: 16,
    height: 16,
    marginRight: 6,
  },
  text: {
    fontSize: 18,
    color: "#fff",
  },
});
