import {Global} from "@/styles/global";
import {Dimensions, StyleSheet} from "react-native";

const {width} = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  mapBox: {flex: 1},
  popupTips: {
    position: "absolute",
    top: (188 / 750) * width,
    left: 0,
    zIndex: 999,
    width: width,
    height: (76 / 750) * width,
    backgroundColor: "#ffda00",
    justifyContent: "center",
    alignItems: "center",
  },
  popupTipsText: {
    fontSize: (32 / 750) * width,
    fontWeight: "500",
    lineHeight: (76 / 750) * width,
    color: "#000",
    textAlign: "center",
  },
  rightControl: {
    position: "absolute",
    top: 140,
    right: 16,
  },
  locationControl: {
    position: "absolute",
    bottom: 120,
    right: 16,
  },
  map: {flex: 1},
  mapCopyright: {position: "absolute", bottom: 0, left: 0, flexDirection: "row", alignItems: "flex-end"},
  iconImg: {width: 40, height: 20},
  copyrightText: {fontSize: 8, color: "#fff"},
  footerButtonGroup: {
    position: "absolute",
    bottom: (42 / 750) * width,
    left: 0,
    zIndex: 1000,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    width: "100%",
    paddingHorizontal: (68 / 750) * width,
  },
  buttonBase: {
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonRevoke: {
    width: (140 / 750) * width,
    height: (140 / 750) * width,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
  },
  revokeText: {fontSize: (36 / 750) * width, fontWeight: "500", color: "#ff3d3b"},
  buttonDot: {
    width: (200 / 750) * width,
    height: (200 / 750) * width,
    backgroundColor: Global.colors.primary,
    borderWidth: (8 / 750) * width,
    borderColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 12},
    shadowOpacity: 0.16,
    shadowRadius: 16,
    elevation: 6,
  },
  dotIcon: {width: (60 / 750) * width, height: (60 / 750) * width, marginBottom: 4},
  dotText: {fontSize: (36 / 750) * width, fontWeight: "500", color: "#fff"},
  buttonSave: {
    width: (140 / 750) * width,
    height: (140 / 750) * width,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
  },
  saveText: {fontSize: (36 / 750) * width, fontWeight: "500"},
  placeholder: {width: (140 / 750) * width, height: (140 / 750) * width},
  locationCursor: {
    position: "absolute",
    top: "50%",
    left: "50%",
    zIndex: 1010,
    transform: [{translateX: -(40 / 750) * width}, {translateY: -(40 / 750) * width}],
  },
  cursorIcon: {width: (80 / 750) * width, height: (80 / 750) * width, resizeMode: "contain"},
});
