import {Dimensions, StyleSheet} from "react-native";

// 底部按钮高度
const BOTTOM_BTN_HEIGHT = 84;

export const LandInfoEditScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    width: Dimensions.get("window").width,
    backgroundColor: "#f5f6f8",
  },
  // 关键修改：增加底部内边距，值等于底部按钮高度
  informationContent: {
    flex: 1,
    width: "100%",
    marginBottom: BOTTOM_BTN_HEIGHT,
    backgroundColor: "#f5f6f8",
  },
  personalInfo: {
    padding: 8,
    marginTop: 8,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: -1},
    shadowOpacity: 0.06,
    shadowRadius: 0,
  },
  landArea: {
    padding: 8,
    marginTop: 8,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: -1},
    shadowOpacity: 0.06,
    shadowRadius: 0,
  },
  landPosition: {
    padding: 8,
    marginTop: 8,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: -1},
    shadowOpacity: 0.06,
    shadowRadius: 0,
  },
  titleContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  mark: {
    width: 4,
    height: 16,
    backgroundColor: "#08ae3c",
    marginRight: 8,
  },
  titleText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#000",
  },
  informationBox: {
    width: "100%",
  },
  informationBoxItem: {
    flexDirection: "row",
    alignItems: "center",
    height: 56,
    borderBottomWidth: 1,
    borderBottomColor: "#e7e7e7",
  },
  lastItem: {
    borderBottomWidth: 0,
  },
  informationText: {
    width: 100,
    fontSize: 16,
    color: "#000",
  },
  informationInput: {
    flex: 1,
    height: "100%",
    fontSize: 18,
    fontWeight: "500",
    color: "#333",
  },
  informationImg: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
  },
  scanIcon: {
    width: 24,
    height: 24,
  },
  rightIcon: {
    width: 24,
    height: 24,
  },
  searchResults: {
    position: "absolute",
    top: 187,
    left: 110,
    right: 44,
    width: 240,
    maxHeight: 310,
    backgroundColor: "#fff",
    borderRadius: 4,
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.08,
    shadowRadius: 4,
    zIndex: 100,
    elevation: 4, // elevation 值越大，阴影越明显（约等于原样式的扩散+模糊效果）
  },
  searchResultItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#e7e7e7",
  },
  name: {
    fontSize: 16,
    color: "#000",
  },
  cardidText: {
    marginTop: 8,
    fontSize: 14,
    color: "#666",
  },
  informationNumber: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 5,
  },
  number: {
    fontSize: 24,
    fontWeight: "500",
    color: "#08ae3c",
  },
  unit: {
    marginLeft: 2.5,
    fontSize: 18,
    fontWeight: "500",
    color: "#000",
  },
  informationArea: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: 172,
    height: 38,
    borderWidth: 1,
    borderColor: "#e4e4e4",
  },
  informationUnit: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    height: 38,
    paddingHorizontal: 12,
    backgroundColor: "#eff2f3",
    borderWidth: 1,
    borderColor: "#e4e4e4",
  },
  unitInput: {
    flex: 1,
    fontSize: 18,
    fontWeight: "500",
    color: "#000",
    textAlign: "center",
    padding: 0,
  },
  unitText: {
    fontSize: 18,
    fontWeight: "500",
    color: "#000",
  },
  informationIcon: {
    width: 38,
    height: 38,
  },
  contractType: {
    flexDirection: "row",
    alignItems: "center",
    height: 52,
    paddingHorizontal: 16,
    marginTop: 8,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: -1},
    shadowOpacity: 0.06,
    shadowRadius: 0,
  },
  contractTitle: {
    marginRight: 41,
    fontSize: 16,
    fontWeight: "400",
    color: "#000",
  },
  contractRadio: {
    flexDirection: "row",
    alignItems: "center",
  },
  radioItem: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 32,
  },
  radioIcon: {
    width: 24,
    height: 24,
  },
  radioText: {
    marginLeft: 8,
    fontSize: 16,
    fontWeight: "500",
    color: "#000",
  },
  btnSave: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: BOTTOM_BTN_HEIGHT, // 使用常量定义高度，方便统一管理
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#e7e7e7",
  },
  btn: {
    width: 344,
    height: 52,
    borderRadius: 8,
    backgroundColor: "#08ae3c",
    justifyContent: "center",
    alignItems: "center",
  },
  btnText: {
    fontSize: 20,
    fontWeight: "500",
    color: "#fff",
  },
  popupOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  popupContainer: {
    width: 300,
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 24,
  },
  popupTitle: {
    fontSize: 18,
    fontWeight: "500",
    color: "#000",
    textAlign: "center",
    marginBottom: 16,
  },
  popupMessage: {
    fontSize: 16,
    color: "#000",
    textAlign: "center",
    marginBottom: 24,
  },
  popupIcon: {
    width: 48,
    height: 48,
    alignSelf: "center",
    marginBottom: 16,
  },
  popupButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  popupButton: {
    width: 120,
    height: 44,
    borderRadius: 4,
    backgroundColor: "#f5f5f5",
    justifyContent: "center",
    alignItems: "center",
  },
  popupRightButton: {
    backgroundColor: "#08ae3c",
  },
  popupButtonText: {
    fontSize: 16,
    color: "#000",
  },
  popupRightButtonText: {
    color: "#fff",
  },
  popupContentMain: {
    paddingHorizontal: 23,
    paddingBottom: 24,
    marginBottom: 24,
  },
  informationItem: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginTop: 8,
  },
  label: {
    width: 78,
    fontSize: 16,
    fontWeight: "400",
    color: "#666",
  },
  text: {
    flex: 1,
    fontSize: 16,
    fontWeight: "400",
    color: "#000",
  },
});
