import {StyleSheet} from "react-native";

export const ScanAddCustomLayerStyles = StyleSheet.create({
  container: {flex: 1, backgroundColor: "#4e4e4f"},
  fullCamera: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#000",
  },
  overlay: {
    position: "absolute",
    top: "26%",
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 0,
  },
  headerOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  bottomOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    top: "52%",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 0,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    height: 44,
    position: "relative",
  },
  headerTitle: {
    position: "absolute",
    left: 0,
    right: 0,
    textAlign: "center",
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
  },
  headerIcon: {
    width: 26,
    height: 26,
    alignItems: "center",
    justifyContent: "center",
  },
  icon: {width: 26, height: 26},
  cameraBox: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  camera: {
    flex: 1,
    width: "100%",
  },
  cameraPlaceholder: {width: 250, height: 250, backgroundColor: "#000"},
  buttonContent: {alignItems: "center", justifyContent: "center"},
  tips: {
    marginTop: 26,
    fontSize: 20,
    fontWeight: "500",
    color: "#fff",
    textAlign: "center",
  },
  buttonBottom: {alignItems: "center", marginTop: 70},
  button: {
    width: 250,
    height: 52,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  btnText: {fontSize: 20, fontWeight: "500", color: "#fff"},
  shot: {marginTop: 24, backgroundColor: "#f58700"},
  photoAlbum: {
    position: "absolute",
    top: "78%",
    left: "50%",
    transform: [{translateX: -32}],
    right: 0,
    bottom: 0,
    width: "100%",
  },
  photoAlbumItem: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "rgba(255,255,255,0.17)",
  },
  photoIcon: {
    width: 32,
    height: 32,
  },
  photoAlbumText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#fff",
  },
});
