import {Global} from "@/styles/global";
import {Dimensions, StyleSheet} from "react-native";

const SCREEN_WIDTH = Dimensions.get("window").width;

export const AddContractScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    width: SCREEN_WIDTH,
    backgroundColor: "#fff",
  },
  msgContent: {
    width: SCREEN_WIDTH,
    height: 670,
    marginBottom: 84,
    backgroundColor: "#f5f6f8",
  },
  contractLease: {
    padding: 16,
    paddingLeft: 7,
    paddingBottom: 0,
    marginTop: 8,
    justifyContent: "center",
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: -1},
    shadowOpacity: 0.06,
    shadowRadius: 0,
  },
  payMsg: {
    padding: 16,
    paddingLeft: 7,
    paddingBottom: 0,
    marginTop: 8,
    justifyContent: "center",
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: -1},
    shadowOpacity: 0.06,
    shadowRadius: 0,
  },
  landMsg: {
    padding: 16,
    paddingLeft: 7,
    paddingBottom: 0,
    marginTop: 8,
    justifyContent: "center",
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: -1},
    shadowOpacity: 0.06,
    shadowRadius: 0,
  },
  partaMsg: {
    padding: 16,
    paddingLeft: 7,
    paddingBottom: 0,
    marginTop: 8,
    justifyContent: "center",
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: -1},
    shadowOpacity: 0.06,
    shadowRadius: 0,
  },
  title: {
    flexDirection: "row",
    alignItems: "center",
    height: 26,
    marginBottom: 6,
  },
  mark: {
    width: 4,
    height: 18,
    backgroundColor: Global.colors.primary,
  },
  titleText: {
    marginLeft: 5,
    fontSize: 18,
    fontWeight: "500",
    color: "#000",
  },
  msgBox: {
    paddingLeft: 9,
  },
  msgBoxItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    height: 52,
  },
  borderBottom: {
    borderBottomWidth: 1,
    borderBottomColor: "#e7e7e7",
  },
  msgText: {
    width: 104,
    fontSize: 18,
    fontWeight: "400",
    color: "#000",
  },
  pickerRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    height: 52,
  },
  msgInput: {
    flex: 1,
    marginLeft: 16,
    fontSize: 18,
    fontWeight: "500",
    color: "#000",
  },
  msgInputText: {
    fontSize: 18,
    fontWeight: "500",
    color: "#000",
  },
  msgImg: {
    width: 26,
    height: 26,
    marginLeft: 5,
  },
  icon: {
    width: "100%",
    height: "100%",
  },
  quarter: {
    height: 57,
  },
  ellipsis: {
    flex: 1,
  },
  landLocation: {
    maxWidth: 250,
  },
  timePicker: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 16,
  },
  timeInput: {
    width: 150,
    height: 38,
    paddingLeft: 12,
    justifyContent: "center",
    fontSize: 18,
    fontWeight: "500",
    backgroundColor: "#eff2f3",
    borderRadius: 4,
  },
  timeSplit: {
    fontSize: 18,
    marginHorizontal: 5,
  },
  rent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 16,
  },
  rentInput: {
    width: 76,
    height: 40,
    fontWeight: "500",
    color: "#000",
    textAlign: "center",
    backgroundColor: "#eff2f3",
    borderWidth: 1,
    borderColor: "#e4e4e4",
    borderRadius: 4,
    fontSize: 16,
    padding: 0,
  },
  rentUnit: {
    marginLeft: 10,
    fontSize: 18,
    fontWeight: "500",
    color: "#000",
  },
  msgArea: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    height: 38,
    marginLeft: 16,
    borderWidth: 1,
    borderColor: "#e4e4e4",
    borderRadius: 4,
  },
  msgUnit: {
    minWidth: 99,
    height: 38,
    fontSize: 18,
    fontWeight: "500",
    color: "#000",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    backgroundColor: "#eff2f3",
    borderWidth: 1,
    borderColor: "#e4e4e4",
  },
  unitText: {
    fontSize: 18,
    fontWeight: "500",
    color: "#000",
  },
  msgIcon: {
    width: 38,
    height: 38,
  },
  btnSave: {
    position: "absolute",
    bottom: 0,
    left: 0,
    alignItems: "center",
    justifyContent: "center",
    width: SCREEN_WIDTH,
    height: 84,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: -1},
    shadowOpacity: 0.1,
    shadowRadius: 0,
  },
  btn: {
    width: 344,
    height: 52,
    fontSize: 20,
    fontWeight: "500",
    lineHeight: 52,
    color: "#fff",
    textAlign: "center",
    backgroundColor: Global.colors.primary,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  btnText: {
    fontSize: 20,
    fontWeight: "500",
    color: "#fff",
  },
  contentItem: {
    width: "100%",
    marginTop: 10,
  },
  label: {
    marginBottom: 8,
    fontSize: 18,
    fontWeight: "500",
    color: "#000",
  },
  input: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: 270,
    height: 48,
    paddingHorizontal: 11,
    paddingRight: 5,
    backgroundColor: "#eff2f3",
    borderRadius: 4,
  },
  content: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: 230,
    fontSize: 18,
    fontWeight: "500",
    color: "#000",
  },
  contentText: {
    fontSize: 18,
    fontWeight: "500",
    color: "#000",
  },
  splitText: {
    fontSize: 18,
  },
  rightIcon: {
    width: 18,
    height: 18,
  },
  dialogText: {
    fontSize: 18,
    textAlign: "center",
    marginVertical: 10,
  },
  dialogBtn: {
    fontSize: 16,
  },
});
