import {StyleSheet} from "react-native";

export const AddDeviceScreenStyles = StyleSheet.create({
  container: {flex: 1, backgroundColor: "#4e4e4f"},
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    height: 44,
    position: "relative",
  },
  headerTitle: {
    position: "absolute",
    left: 0,
    right: 0,
    textAlign: "center",
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
  },
  headerIcon: {
    width: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  icon: {width: 26, height: 26},
  cameraBox: {marginTop: 102, alignItems: "center", justifyContent: "center"},
  camera: {width: 250, height: 250, borderRadius: 8},
  cameraPlaceholder: {width: 250, height: 250, backgroundColor: "#000"},
  buttonContent: {alignItems: "center", justifyContent: "center"},
  tips: {
    marginTop: 26,
    fontSize: 20,
    fontWeight: "500",
    color: "#fff",
    textAlign: "center",
  },
  buttonBottom: {alignItems: "center", marginTop: 50},
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    width: 250,
    height: 20,
    justifyContent: "center",
  },
  line: {width: 90, height: 1, backgroundColor: "#fff", opacity: 0.7},
  text: {
    textAlign: "center",
    paddingHorizontal: 12,
    color: "#fff",
    backgroundColor: "#4e4e4f",
  },
  button: {
    width: 250,
    height: 52,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  btnText: {fontSize: 20, fontWeight: "500", color: "#fff"},
  shot: {marginTop: 24, backgroundColor: "#f58700"},
  hand: {marginTop: 20, backgroundColor: "#08ae3c"},
  bluetooth: {marginTop: 16, backgroundColor: "#007cff"},
  popupContent: {
    position: "absolute",
    top: "50%",
    left: "10%",
    right: "10%",
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 16,
  },
  popupContentTop: {alignItems: "center"},
  title: {fontSize: 20, fontWeight: "500", color: "#000", marginTop: 16},
  msg: {fontSize: 16, color: "#000", marginTop: 16, textAlign: "center"},
  divider: {height: 1, backgroundColor: "#ededed", marginVertical: 8},
  popupBottom: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingVertical: 12,
  },
  btnLeft: {fontSize: 18, color: "#000"},
  btnRight: {fontSize: 18, color: "#08ae3c"},
  cross: {width: 1, height: 20, backgroundColor: "#ededed"},
});
